name: Flutter CI

env:
  version: 1.0.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter build apk

      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - uses: actions/upload-artifact@v4
        with:
          name: green_buddies_v${{steps.yq.outputs.result}}
          path: build/app/outputs/apk/release/app-release.apk
